apiVersion: v1
kind: Pod
metadata:
  name: web-go
spec:
  containers:
    - name: rest
      image: web-go:v1
      command: ["rest"]
      env:
        - name: GIN_MODE
          value: "release"
        - name: REST_ADDR
          value: "0.0.0.0:8080"
      ports:
        - containerPort: 8080
    - name: filter
      image: web-go:v1
      command: ["filter"]
    - name: notifications
      image: web-go:v1
      command: ["notifications"]
    - name: broker
      image: apache/kafka:3.9.1
