apiVersion: v1
kind: Pod
metadata:
  name: web-go
spec:
  # don't forget to relabel this sheisse (chcon -t container_file_t -R frontend/ nginx/)
  volumes:
  - name: conf
    hostPath:
      path: nginx
      type: Directory
  - name: static
    hostPath:
      path: frontend
      type: Directory
  containers:
    - name: proxy
      image: nginx:latest
      ports:
        - containerPort: 80
          hostPort: 8080
      volumeMounts:
      - name: conf
        mountPath: /etc/nginx/conf.d
      - name: static
        mountPath: /www
    - name: rest
      image: &mega_img web-go:latest
      command: ["rest"]
      env:
        - name: GIN_MODE
          value: "release"
        - name: REST_ADDR
          value: "0.0.0.0:8080"
    - name: filter
      image: *mega_img
      command: ["filter"]
    - name: notifications
      image: *mega_img
      command: ["notifications"]
    - name: broker
      image: apache/kafka:3.9.1
